config/routes.rb
Rails.application.routes.draw do
  resources :pollbooths
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pollbooths#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pollbooth.rb
class Pollbooth < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pollbooths_controller.rb
class PollboothsController < ApplicationController
  before_action :set_pollbooth, only: [:show, :edit, :update, :destroy]

  # GET /pollbooths
  # GET /pollbooths.json
  def index
    @pollbooths = Pollbooth.all
  end

  # GET /pollbooths/1
  # GET /pollbooths/1.json
  def show
  end

  # GET /pollbooths/new
  def new
    @pollbooth = Pollbooth.new
  end

  # GET /pollbooths/1/edit
  def edit
  end

  # POST /pollbooths
  # POST /pollbooths.json
  def create
    @pollbooth = Pollbooth.new(pollbooth_params)

    respond_to do |format|
      if @pollbooth.save
        format.html { redirect_to @pollbooth, notice: 'Pollbooth was successfully created.' }
        format.json { render :show, status: :created, location: @pollbooth }
      else
        format.html { render :new }
        format.json { render json: @pollbooth.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pollbooths/1
  # PATCH/PUT /pollbooths/1.json
  def update
    respond_to do |format|
      if @pollbooth.update(pollbooth_params)
        format.html { redirect_to @pollbooth, notice: 'Pollbooth was successfully updated.' }
        format.json { render :show, status: :ok, location: @pollbooth }
      else
        format.html { render :edit }
        format.json { render json: @pollbooth.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pollbooths/1
  # DELETE /pollbooths/1.json
  def destroy
    @pollbooth.destroy
    respond_to do |format|
      format.html { redirect_to pollbooths_url, notice: 'Pollbooth was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pollbooth
      @pollbooth = Pollbooth.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pollbooth_params
      params.require(:pollbooth).permit(:email, :answer)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pollbooths_helper.rb
module PollboothsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <div class="alert alert-info" role="alert">
    <title>Polls</title>
    </div>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body background ="https://png.pngtree.com/thumb_back/fw800/back_pic/00/14/24/00565ab1bf5328f.jpg">
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/pollbooths/_form.html.erb
<div class=container>
<%= form_with(model: pollbooth, local: true) do |form| %>
  <% if pollbooth.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pollbooth.errors.count, "error") %> prohibited this pollbooth from being saved:</h2>

      <ul>
      <% pollbooth.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

<h3><strong>Choose whichever Option pleases you the most</strong></h3>

<br>

  <div class="form-group">
    <%= form.label :answer %>
    <%= form.select :answer,['Option 1', 'Option 2', 'Option 3', 'Option 4'] %>
  </div>
<br>
  <div class="form-group">
    <%= form.submit value="Vote!!" %>
  </div>
 
<% end %>
</div>

app/views/pollbooths/edit.html.erb
<div class="alert alert-info" role="alert">
<h1>Editing Pollbooth</h1>
</div>
<%= render 'form', pollbooth: @pollbooth %>

app/views/pollbooths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pollbooths</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Answer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pollbooths.each do |pollbooth| %>
      <tr>
        <td><%= pollbooth.email %></td>
        <td><%= pollbooth.answer %></td>
        <td><%= link_to 'Show', pollbooth %></td>
        <td><%= link_to 'Edit', edit_pollbooth_path(pollbooth) %></td>
        <td><%= link_to 'Destroy', pollbooth, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pollbooth', new_pollbooth_path %>

app/views/pollbooths/new.html.erb
<div class="alert alert-info" role="alert">
<h1>Polling station</h1>
</div>
<%= render 'form', pollbooth: @pollbooth %>


<%= pie_chart Pollbooth.group(:answer).count %>
<br>

<%= bar_chart Pollbooth.group(:answer).count %>
</div>

app/views/pollbooths/show.html.erb
<div class="container">
<h1>Vote registered Succesfully</h1>
<br>
<h4>
  <strong>Email:</strong>
  <%= @pollbooth.email %>
</h4>
<br>
<h4>
  <strong>Answer:</strong>
  <%= @pollbooth.answer %>
</h4>
<br>
<div class="form-group">
<%= link_to '<button type="button">Edit Response</button>'.html_safe, edit_pollbooth_path(@pollbooth) %> |
<%= link_to '<button type="button">Cast another vote</button>'.html_safe, new_pollbooth_path %>
</div>
</div>